# Generated by Django 2.2.1 on 2019-06-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0006_auto_20190606_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest1',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.College'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineapp.College'),
        ),
    ]
